version: 2
updates:
  # .github/workflows/*.yml
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Europe/London
    groups:
      default:
        patterns:
          - "*"

  # package.json
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Europe/London
    groups:
      default:
        patterns:
          - "*"
